version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: igomezdockerhub/reverseproxy:v4
  backend_user:
    build:
      context: ./udagram-api-user
    image: igomezdockerhub/udagram-api-user:v4
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: igomezdockerhub/udagram-api-feed:v4
  frontend:
    build:
      context: ./udagram-frontend
    image: igomezdockerhub/udagram-frontend:v4