apiVersion: v1
kind: Service
metadata:
  labels:
    run: backend-user
  name: backend-user
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: backend-user 